'use client';

import { useEffect } from 'react';
import config from '../config';
import ContactForm from '../components/ContactForm';

const appLink = config.appLink;
const whatsappLink = `https://wa.me/${String(config.whatsappNumber).replace(/\D/g, '')}?text=${encodeURIComponent(config.whatsappDefaultMessage)}`;

function SectionLabel({ number, children }) { return <div className="section-label"><span>{number}</span><span className="label-rule"></span><span>{children}</span></div>; }
function Button({ children, href = '/contact', dark = false }) { return <a className={`button ${dark ? 'button-dark' : 'button-primary'}`} href={href}>{children}<span aria-hidden="true">↗</span></a>; }

export default function HomePage() {
  useEffect(() => {
    const items = document.querySelectorAll('.reveal');
    const observer = new IntersectionObserver((entries, io) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); io.unobserve(entry.target); } }), { threshold: .12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);

  return <main>
    <section className="hero section-pad"><div className="paper-grain" aria-hidden="true"></div><div className="container hero-grid">
      <div className="hero-copy reveal"><p className="eyebrow"><span className="eyebrow-dot"></span>The everyday TV network</p><h1>Your TV is<br />already <em>there.</em></h1><p className="hero-lede">Let’s make it useful.</p><p className="hero-description">Every day, people are already looking at screens in restaurants, clinics, salons, cafés, waiting rooms, and shops. MyReach helps those screens do more.</p><div className="hero-actions"><Button href="/contact">Put my screen to work</Button><a className="text-link" href="/contact">I’m an advertiser <span aria-hidden="true">→</span></a></div><div className="hero-footnote"><span className="tiny-star">✳</span>Built for places people already trust.</div></div>
      <div className="hero-visual reveal reveal-delay"><div className="scribble scribble-top">your place<br /><span>your rules</span></div><div className="floating-note note-yellow"><strong>50%</strong><span>your time</span></div><div className="floating-note note-coral"><strong>0</strong><span>competitor ads</span></div><div className="tv-shadow"></div><div className="tv-set"><div className="tv-bezel"><div className="tv-screen"><div className="screen-topline"><span className="live-dot"></span>MYREACH / LIVE</div><div className="screen-content"><span className="screen-kicker">A good place to</span><strong>pause<br /><i>&amp; look.</i></strong><span className="screen-rule"></span><span className="screen-ad">TODAY’S POUR<br /><b>IS ON US</b></span></div><div className="screen-footer"><span>YOUR MENU</span><span>01 / 04</span></div></div></div><div className="tv-led"></div><div className="tv-stand"></div></div><div className="floating-note note-lime"><span>relevant ads</span><strong>right here</strong></div><div className="visual-caption"><span className="caption-line"></span><span>idle time, made useful</span></div></div>
    </div><div className="scroll-cue" aria-hidden="true"><span>scroll to explore</span><i>↓</i></div></section>

    <section className="audience-strip"><div className="marquee-track"><span>Restaurants</span><i>✳</i><span>Clinics</span><i>✳</i><span>Cafés</span><i>✳</i><span>Salons</span><i>✳</i><span>Stores</span><i>✳</i><span>Waiting rooms</span><i>✳</i><span>Restaurants</span><i>✳</i><span>Clinics</span><i>✳</i><span>Cafés</span><i>✳</i><span>Salons</span><i>✳</i></div></section>

    <section className="intro section-pad" id="how-it-works"><div className="container intro-grid"><div className="section-label reveal"><span>01</span><span className="label-rule"></span><span>THE IDEA</span></div><div className="intro-content reveal reveal-delay"><h2>Turn an idle TV<br />into a <em>living</em> touchpoint.</h2><p>MyReach changes the role of the screen already in your space. Keep using it as you do today. We simply help the unused moments carry something valuable.</p><div className="promise-row"><div className="promise"><span className="promise-icon">◒</span><span>People are<br /><strong>already looking.</strong></span></div><div className="promise"><span className="promise-icon">↗</span><span>Brands are<br /><strong>already looking for them.</strong></span></div></div></div></div></section>

    <section className="split-feature section-pad" id="screen-owners"><div className="container"><div className="section-heading reveal"><SectionLabel number="02">FOR SCREEN OWNERS</SectionLabel><span className="section-stamp">your screen, your space</span></div><div className="owner-grid"><div className="owner-copy reveal"><h2>Keep your TV.<br /><em>Share the spare.</em></h2><p>Install the MyReach TV app, connect your screen, and let the platform handle the rest. Your content stays yours; unused advertising time starts working for you.</p><a className="button button-dark" href={appLink} download={config.appFileName}>Download the TV app <span aria-hidden="true">↗</span></a></div><div className="fifty-card reveal reveal-delay"><div className="card-doodle">✳</div><p className="card-overline">A simple split</p><div className="split-bar"><span className="split-yours">50%</span><span className="split-mine">50%</span></div><div className="split-labels"><span><b>Your time</b><br />Offers · menu · news</span><span><b>MyReach time</b><br />Relevant brand stories</span></div><div className="card-note">You provide the screen.<br /><em>We bring the advertisers.</em></div></div></div><div className="owner-benefits reveal"><div><span className="benefit-icon">⌁</span><span><b>No complicated setup.</b> Connect and go.</span></div><div><span className="benefit-icon">↗</span><span><b>No selling advertisers.</b> We handle the network.</span></div><div><span className="benefit-icon">⊘</span><span><b>No competitor ads.</b> Your category stays protected.</span></div></div></div></section>

    <section className="partner-features section-pad"><div className="container"><div className="partner-heading reveal"><div><SectionLabel number="03">MYREACH SCREEN PARTNER</SectionLabel><h2>More than a screen.<br /><em>A marketing tool.</em></h2></div><p>We help you turn the TV you already own into a useful, always-on way to promote your business.</p></div><div className="partner-feature-grid"><article className="partner-feature-card feature-highlight reveal"><span className="partner-feature-icon">✳</span><div><h3>Promote your business</h3><p>Show products, services, offers, menus, new arrivals, promotions, contact details, and clear calls to action.</p><div className="feature-tags"><span>Products</span><span>Offers</span><span>Menus</span><span>CTAs</span></div></div></article><article className="partner-feature-card reveal reveal-delay"><span className="partner-feature-icon">✎</span><div><h3>We create the content</h3><p>No designer or marketing team needed. MyReach can create polished 15–30 second promotional creatives for your business.</p></div></article><article className="partner-feature-card reveal"><span className="partner-feature-icon">◎</span><div><h3>Your business stays the focus</h3><p>Your own content remains the core content displayed on your screen throughout the day.</p></div></article><article className="partner-feature-card reveal reveal-delay"><span className="partner-feature-icon">⌁</span><div><h3>Fresh content, regularly updated</h3><p>Keep promotions current as your offers, products, services, and campaigns change.</p></div></article><article className="partner-feature-card reveal"><span className="partner-feature-icon">⌖</span><div><h3>Reach customers where they are</h3><p>Your promotions appear inside your own business, helping customers discover more while they are already there.</p></div></article><article className="partner-feature-card reveal reveal-delay"><span className="partner-feature-icon">↗</span><div><h3>Become part of a local network</h3><p>Your display joins a growing network of businesses and digital screens across the local area.</p></div></article></div><div className="partner-footer-note reveal"><span className="benefit-icon">⚡</span><span><b>Simple setup.</b> You provide the existing TV or display. MyReach handles the promotional content and network management.</span></div></div></section>

    <section className="guardrail section-pad"><div className="container guardrail-grid"><div className="guardrail-copy reveal"><SectionLabel number="03">THE PROMISE</SectionLabel><h2>Your competitors<br />won’t appear<br /><em>on your screen.</em></h2><p>Your business shouldn’t have to promote someone else’s business in the space you provide. MyReach protects your category, so the audience stays useful to you.</p></div><div className="guardrail-art reveal reveal-delay"><div className="protection-card"><div className="protection-top"><span className="shield">♢</span><span>MYREACH / PROTECTED</span><span>100%</span></div><div className="protection-main"><span>your</span><strong>space</strong><span>stays yours.</span></div><div className="protection-bottom"><span className="strike-circle">×</span><span>No same-industry ads</span></div></div><div className="red-sticker">NOT<br /><b>YOUR<br />COMPETITOR.</b></div></div></div><div className="container category-wrap reveal"><div className="category-intro"><span>Instead, meet</span><strong>complementary<br />categories.</strong></div><div className="category-list"><span className="category category-lime">Biscuits</span><span className="category category-coral">Beverages</span><span className="category category-blue">Wellness</span><span className="category category-yellow">Personal care</span><span className="category category-purple">Insurance</span><span className="category category-teal">Real estate</span><span className="category category-orange">Education</span></div></div></section>

    <section className="principle section-pad"><div className="container principle-grid"><div className="principle-mark">↗</div><div className="principle-copy reveal"><SectionLabel number="04">THE MYREACH WAY</SectionLabel><p className="large-quote">Advertise <em>around</em><br />the business.</p><p className="large-quote muted">Never <span>against</span> it.</p><p className="principle-description">A restaurant gets to be a restaurant. A clinic gets to be a clinic. We build an advertising environment that respects the place, while giving relevant brands a better moment to be seen.</p></div><div className="place-card reveal reveal-delay"><div className="place-screen"><span className="place-label">INSIDE YOUR LOCAL</span><strong>Eat well.<br /><i>Live well.</i></strong><div className="place-ad">+ a little something<br /><b>for later</b></div></div><div className="place-caption"><span>the right message</span><b>in the right place.</b></div></div></div></section>

    <section className="advertiser section-pad" id="advertisers"><div className="container advertiser-grid"><div className="advertiser-art reveal"><div className="map-dots"></div><div className="reach-card reach-card-main"><span className="reach-card-top">MYREACH / CAMPAIGN</span><strong>Be there<br /><em>when they are.</em></strong><span className="reach-pin">⌖ YOUR AUDIENCE</span></div><div className="reach-card reach-card-small"><span>LIVE IN</span><strong>12</strong><span>PLACES NEARBY</span></div></div><div className="advertiser-copy reveal reveal-delay"><SectionLabel number="05">FOR ADVERTISERS</SectionLabel><h2>Don’t just advertise online.<br /><em>Be there.</em></h2><p>Reach people in the places where they are already spending time. Put your message on relevant screens, in relevant spaces, at the right moment.</p><div className="reach-filters"><span>Location</span><span>Venue</span><span>Audience</span><span>Time</span><span>Campaign</span></div><Button href="/contact">Plan a campaign</Button></div></div></section>

    <section className="network section-pad"><div className="container network-grid"><div className="network-copy reveal"><SectionLabel number="06">THE NETWORK</SectionLabel><h2>One network.<br /><em>Everyday screens.</em></h2><p>Every new screen expands the network. Every new advertiser makes it more valuable. Together, they create a local advertising layer powered by TVs that already exist.</p></div><div className="network-map reveal reveal-delay"><svg viewBox="0 0 560 370" aria-hidden="true"><path className="map-line" d="M105 88 C182 63 194 164 280 132 S390 70 456 124" /><path className="map-line" d="M105 88 C170 210 205 284 302 250 S408 202 456 124" /><path className="map-line" d="M280 132 C291 184 286 217 302 250" /><path className="map-line" d="M302 250 C365 284 410 290 478 267" /><g className="node node-one"><circle cx="105" cy="88" r="25" /><text x="105" y="93">TV</text></g><g className="node node-two"><circle cx="280" cy="132" r="30" /><text x="280" y="137">TV</text></g><g className="node node-three"><circle cx="456" cy="124" r="23" /><text x="456" y="129">TV</text></g><g className="node node-four"><circle cx="302" cy="250" r="24" /><text x="302" y="255">TV</text></g><g className="node node-five"><circle cx="478" cy="267" r="29" /><text x="478" y="272">TV</text></g></svg><div className="map-tag tag-one">restaurant</div><div className="map-tag tag-two">clinic</div><div className="map-tag tag-three">café</div><div className="map-tag tag-four">salon</div></div></div></section>

    <section className="contact section-pad" id="contact"><div className="container contact-grid"><div className="contact-copy reveal"><SectionLabel number="07">LET’S TALK</SectionLabel><h2>Have a screen?<br />Have a <em>campaign?</em></h2><p>Tell us what you are building. We will help you find the right way to make your screen, space, or campaign work harder.</p><div className="contact-details"><a className="contact-direct" href={whatsappLink} target="_blank" rel="noreferrer"><span className="contact-icon">◌</span><span><b>Chat with {config.contactName}</b><small>{config.contactAvailability}</small></span><span className="contact-arrow">↗</span></a><a className="contact-direct" href={`mailto:${config.contactEmail}`}><span className="contact-icon">@</span><span><b>{config.contactEmail}</b><small>Email works too</small></span><span className="contact-arrow">↗</span></a></div></div><div className="reveal reveal-delay"><ContactForm /></div></div></section>

    <section className="final-cta section-pad" id="get-started"><div className="container final-cta-inner reveal"><div className="final-spark">✳</div><p className="eyebrow"><span className="eyebrow-dot"></span>Start with the screen you have</p><h2>Your TV is already<br /><em>reaching people.</em></h2><p>The question is: what should it reach them with?</p><div className="final-actions"><a className="button button-light" href="/contact">Get started <span aria-hidden="true">↗</span></a><a className="outline-link" href={appLink} download={config.appFileName}>Download TV app <span aria-hidden="true">↗</span></a></div></div></section>
  </main>;
}
